import { Post } from "@/types/post.Type";

export const posts : Post[] = [
  {
    id: 1,
    author: "John Doe",
    headline: "Software Engineer @ Google",
    avatar: "https://i.pravatar.cc/150?img=1",
    time: "2h",
    text: "Just completed my LinkedIn clone using Next.js 🚀",
    image: "https://picsum.photos/700/400?random=1",
    likes: 482,
    comments: 31,
    reposts: 12,
  },
  {
    id: 2,
    author: "Sarah Wilson",
    headline: "Frontend Developer @ Microsoft",
    avatar: "https://i.pravatar.cc/150?img=5",
    time: "5h",
    text: "React Server Components are changing the way we build apps.",
    image: "https://picsum.photos/700/400?random=2",
    likes: 101,
    comments: 8,
    reposts: 3,
  },
  {
    id: 3,
    author: "Alex Johnson",
    headline: "Backend Engineer @ Netflix",
    avatar: "https://i.pravatar.cc/150?img=8",
    time: "7h",
    text: "Redis caching reduced our API response time by 60%.",
    image: "https://picsum.photos/700/400?random=3",
    likes: 312,
    comments: 27,
    reposts: 16,
  },
  {
    id: 4,
    author: "Emily Davis",
    headline: "UI/UX Designer",
    avatar: "https://i.pravatar.cc/150?img=9",
    time: "9h",
    text: "Minimal design always wins. Simplicity is powerful.",
    image: "https://picsum.photos/700/400?random=4",
    likes: 541,
    comments: 48,
    reposts: 20,
  },
  {
    id: 5,
    author: "Michael Brown",
    headline: "DevOps Engineer @ Amazon",
    avatar: "https://i.pravatar.cc/150?img=12",
    time: "11h",
    text: "Finally deployed Kubernetes monitoring with Prometheus + Grafana.",
    image: "https://picsum.photos/700/400?random=5",
    likes: 289,
    comments: 15,
    reposts: 9,
  },
  {
    id: 6,
    author: "Sophia Taylor",
    headline: "Data Scientist",
    avatar: "https://i.pravatar.cc/150?img=15",
    time: "13h",
    text: "Python continues to dominate the AI ecosystem.",
    image: "https://picsum.photos/700/400?random=6",
    likes: 623,
    comments: 62,
    reposts: 29,
  },
  {
    id: 7,
    author: "Daniel Martinez",
    headline: "Full Stack Developer",
    avatar: "https://i.pravatar.cc/150?img=18",
    time: "15h",
    text: "Built an authentication system using JWT and refresh tokens.",
    image: "https://picsum.photos/700/400?random=7",
    likes: 177,
    comments: 10,
    reposts: 4,
  },
  {
    id: 8,
    author: "Olivia White",
    headline: "Product Manager",
    avatar: "https://i.pravatar.cc/150?img=20",
    time: "18h",
    text: "A great product starts with understanding users.",
    image: "https://picsum.photos/700/400?random=8",
    likes: 398,
    comments: 19,
    reposts: 8,
  },
  {
    id: 9,
    author: "William Moore",
    headline: "Cloud Architect",
    avatar: "https://i.pravatar.cc/150?img=21",
    time: "20h",
    text: "AWS ECS vs Kubernetes—what's your preference?",
    image: "https://picsum.photos/700/400?random=9",
    likes: 244,
    comments: 29,
    reposts: 6,
  },
  {
    id: 10,
    author: "Emma Harris",
    headline: "Software Engineer @ Meta",
    avatar: "https://i.pravatar.cc/150?img=22",
    time: "1d",
    text: "TypeScript makes large codebases much easier to maintain.",
    image: "https://picsum.photos/700/400?random=10",
    likes: 813,
    comments: 84,
    reposts: 35,
  },
  {
    id: 11,
    author: "James Clark",
    headline: "Cybersecurity Analyst",
    avatar: "https://i.pravatar.cc/150?img=23",
    time: "1d",
    text: "Always enable MFA. Security starts with small habits.",
    image: "https://picsum.photos/700/400?random=11",
    likes: 342,
    comments: 22,
    reposts: 14,
  },
  {
    id: 12,
    author: "Ava Lewis",
    headline: "Machine Learning Engineer",
    avatar: "https://i.pravatar.cc/150?img=24",
    time: "1d",
    text: "Fine-tuning LLMs is easier than ever with open-source tooling.",
    image: "https://picsum.photos/700/400?random=12",
    likes: 754,
    comments: 71,
    reposts: 33,
  },
  {
    id: 13,
    author: "Benjamin Walker",
    headline: "Frontend Engineer",
    avatar: "https://i.pravatar.cc/150?img=25",
    time: "2d",
    text: "Tailwind CSS speeds up UI development dramatically.",
    image: "https://picsum.photos/700/400?random=13",
    likes: 436,
    comments: 34,
    reposts: 17,
  },
  {
    id: 14,
    author: "Charlotte Hall",
    headline: "Technical Recruiter",
    avatar: "https://i.pravatar.cc/150?img=26",
    time: "2d",
    text: "Looking to hire experienced React developers.",
    image: "https://picsum.photos/700/400?random=14",
    likes: 278,
    comments: 41,
    reposts: 12,
  },
  {
    id: 15,
    author: "Henry Allen",
    headline: "Mobile Developer",
    avatar: "https://i.pravatar.cc/150?img=27",
    time: "2d",
    text: "Flutter 4 looks incredibly promising!",
    image: "https://picsum.photos/700/400?random=15",
    likes: 192,
    comments: 11,
    reposts: 5,
  },
  {
    id: 16,
    author: "Grace Young",
    headline: "AI Researcher",
    avatar: "https://i.pravatar.cc/150?img=28",
    time: "3d",
    text: "AI is becoming an essential productivity tool.",
    image: "https://picsum.photos/700/400?random=16",
    likes: 901,
    comments: 92,
    reposts: 46,
  },
  {
    id: 17,
    author: "Lucas King",
    headline: "SRE Engineer",
    avatar: "https://i.pravatar.cc/150?img=29",
    time: "3d",
    text: "Observability > Monitoring.",
    image: "https://picsum.photos/700/400?random=17",
    likes: 366,
    comments: 24,
    reposts: 11,
  },
  {
    id: 18,
    author: "Mia Scott",
    headline: "Frontend Engineer",
    avatar: "https://i.pravatar.cc/150?img=30",
    time: "3d",
    text: "Dark mode or Light mode? Which do you prefer?",
    image: "https://picsum.photos/700/400?random=18",
    likes: 599,
    comments: 79,
    reposts: 22,
  },
  {
    id: 19,
    author: "Ethan Green",
    headline: "Software Engineer",
    avatar: "https://i.pravatar.cc/150?img=31",
    time: "4d",
    text: "Just solved 500 LeetCode problems 🎉",
    image: "https://picsum.photos/700/400?random=19",
    likes: 1124,
    comments: 145,
    reposts: 63,
  },
  {
    id: 20,
    author: "Harper Adams",
    headline: "Engineering Manager",
    avatar: "https://i.pravatar.cc/150?img=32",
    time: "4d",
    text: "Great teams are built on trust and communication.",
    image: "https://picsum.photos/700/400?random=20",
    likes: 477,
    comments: 28,
    reposts: 15,
  },
  {
    id: 21,
    author: "David Turner",
    headline: "Blockchain Developer",
    avatar: "https://i.pravatar.cc/150?img=33",
    time: "5d",
    text: "Web3 continues to evolve despite market fluctuations.",
    image: "https://picsum.photos/700/400?random=21",
    likes: 238,
    comments: 18,
    reposts: 7,
  },
  {
    id: 22,
    author: "Ella Parker",
    headline: "QA Engineer",
    avatar: "https://i.pravatar.cc/150?img=34",
    time: "5d",
    text: "Automated testing saves countless hours.",
    image: "https://picsum.photos/700/400?random=22",
    likes: 196,
    comments: 12,
    reposts: 5,
  },
  {
    id: 23,
    author: "Matthew Evans",
    headline: "React Native Developer",
    avatar: "https://i.pravatar.cc/150?img=35",
    time: "5d",
    text: "Building cross-platform apps has never been easier.",
    image: "https://picsum.photos/700/400?random=23",
    likes: 341,
    comments: 20,
    reposts: 8,
  },
  {
    id: 24,
    author: "Lily Collins",
    headline: "Software Engineer @ Apple",
    avatar: "https://i.pravatar.cc/150?img=36",
    time: "6d",
    text: "SwiftUI keeps getting better every year.",
    image: "https://picsum.photos/700/400?random=24",
    likes: 688,
    comments: 55,
    reposts: 27,
  },
  {
    id: 25,
    author: "Christopher Hill",
    headline: "Solutions Architect",
    avatar: "https://i.pravatar.cc/150?img=37",
    time: "6d",
    text: "Cloud-native architecture is the future.",
    image: "https://picsum.photos/700/400?random=25",
    likes: 355,
    comments: 18,
    reposts: 10,
  },
  {
    id: 26,
    author: "Zoe Campbell",
    headline: "Graphic Designer",
    avatar: "https://i.pravatar.cc/150?img=38",
    time: "1w",
    text: "Design isn't just how it looks; it's how it works.",
    image: "https://picsum.photos/700/400?random=26",
    likes: 577,
    comments: 37,
    reposts: 19,
  },
  {
    id: 27,
    author: "Andrew Roberts",
    headline: "Tech Lead",
    avatar: "https://i.pravatar.cc/150?img=39",
    time: "1w",
    text: "Code reviews are one of the best learning opportunities.",
    image: "https://picsum.photos/700/400?random=27",
    likes: 467,
    comments: 30,
    reposts: 14,
  },
  {
    id: 28,
    author: "Natalie Perez",
    headline: "Software Engineer",
    avatar: "https://i.pravatar.cc/150?img=40",
    time: "1w",
    text: "Learning Docker and Kubernetes was worth the effort.",
    image: "https://picsum.photos/700/400?random=28",
    likes: 521,
    comments: 33,
    reposts: 16,
  },
  {
    id: 29,
    author: "Ryan Mitchell",
    headline: "AI Engineer",
    avatar: "https://i.pravatar.cc/150?img=41",
    time: "1w",
    text: "Multi-agent AI systems are the next big thing.",
    image: "https://picsum.photos/700/400?random=29",
    likes: 884,
    comments: 97,
    reposts: 44,
  },
  {
    id: 30,
    author: "Isabella Brooks",
    headline: "Software Developer",
    avatar: "https://i.pravatar.cc/150?img=42",
    time: "2w",
    text: "Consistency beats motivation every single time.",
    image: "https://picsum.photos/700/400?random=30",
    likes: 645,
    comments: 54,
    reposts: 21,
  },
];